package com.example.mobileapp.presentation

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.mobileapp.domain.model.Task
import com.example.mobileapp.domain.repository.UserRepository
import com.example.mobileapp.domain.usecase.AddTaskUseCase
import com.example.mobileapp.domain.usecase.GetTasksUseCase
import com.example.mobileapp.domain.usecase.ToggleTaskCompletionUseCase
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.launch

class QuestViewModel(
    private val getTasksUseCase: GetTasksUseCase,
    private val addTaskUseCase: AddTaskUseCase,
    private val toggleTaskCompletionUseCase: ToggleTaskCompletionUseCase,
    private val userRepository: UserRepository,
    private val userId: String
) : ViewModel() {

    private val _tasks = MutableStateFlow<List<Task>>(emptyList())
    val tasks: StateFlow<List<Task>> = _tasks.asStateFlow()

    private val _isLoading = MutableStateFlow(false)
    val isLoading: StateFlow<Boolean> = _isLoading.asStateFlow()

    private val _error = MutableStateFlow<String?>(null)
    val error: StateFlow<String?> = _error.asStateFlow()

    init {
        loadTasks()
    }

    private fun loadTasks() {
        viewModelScope.launch {
            _isLoading.value = true
            getTasksUseCase()
                .onSuccess { taskList ->
                    _tasks.value = taskList
                    _isLoading.value = false
                }
                .onFailure { e ->
                    _error.value = "Firestore Error: ${e.message}"
                    _isLoading.value = false
                }
        }
    }

    fun addTask(title: String, priority: String = "normal") {
        if (title.isBlank()) return

        viewModelScope.launch {
            val newTask = Task(
                id = "", // Generated by repository
                userId = userId,
                title = title,
                description = "",
                dueAt = 0,
                completed = false,
                priority = priority,
                createdAt = System.currentTimeMillis(),
                updatedAt = System.currentTimeMillis()
            )
            val result = addTaskUseCase(newTask)
            if (result.isSuccess) {
                loadTasks()
            } else {
                _error.value = "Failed to add quest"
            }
        }
    }

    fun toggleTask(taskId: String, completed: Boolean) {
        viewModelScope.launch {
            val task = _tasks.value.find { it.id == taskId } ?: return@launch
            val result = toggleTaskCompletionUseCase(taskId, completed)
            if (result.isSuccess) {
                loadTasks()
                // Fetch current user profile to ensure we don't drop below 0 EXP
                userRepository.getUserProfile(userId).onSuccess { user ->
                    val baseExp = when (task.priority) {
                        "high" -> 50
                        "normal" -> 20
                        else -> 10
                    }
                    val expAmount = if (completed) baseExp else -baseExp
                    // Ensure total EXP doesn't go below 0
                    if (user.exp + expAmount >= 0) {
                        userRepository.awardExp(userId, expAmount)
                    } else if (user.exp > 0) {
                        // If it would go below 0, just deduct what's left
                        userRepository.awardExp(userId, -user.exp)
                    }
                }
            }

            if (result.isFailure) {
                _error.value = "Failed to update quest status"
            }
        }
    }
    
    fun clearError() {
        _error.value = null
    }
}
